version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
